import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <div className="w-full px-6 pb-12 antialiased bg-white">
        <div className="mx-auto max-w-8xl">
          <Header></Header>
          <div className="dark:bg-gray-900 mt-6">
              {children}
          </div>
          <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
